## Numpy, Pandas and Matplotlib

#### 1. Write a program to generate an array of 30 numbers (1 to 30) of all possible shapes.

In [106]:
import numpy as np

def genShapes(a):
    """
        This function generates all possible of numpy array
        arg - numpy array
    """
    cnt = 1
    l = len(a)
    
    while cnt <= l:
        if l%cnt==0:
            x = int(l/cnt)
            y = cnt
            print(a.reshape(x,y))
        cnt+=1
    
a = np.array(range(1,31))
genShapes(a)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]
 [25 26]
 [27 28]
 [29 30]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27 28 29 30]]


#### 2. Write a program to generate an array of random integer numbers between 10 to 50 numbers of all possible shapes.

In [52]:
def genShapes(a):
    """
        This function generates all possible of numpy array
        arg - numpy array
    """
    cnt = 1
    l = len(a)
    
    while cnt <= l:
        if l%cnt==0:
            x = int(l/cnt)
            y = cnt
            print(a.reshape(x,y))
        cnt+=1

a = np.random.randint(10,50,30)
genShapes(a)

[[19]
 [33]
 [45]
 [14]
 [21]
 [38]
 [41]
 [32]
 [33]
 [12]
 [13]
 [31]
 [35]
 [15]
 [18]
 [46]
 [34]
 [47]
 [12]
 [42]
 [34]
 [26]
 [27]
 [42]
 [10]
 [24]
 [48]
 [12]
 [15]
 [26]]
[[19 33]
 [45 14]
 [21 38]
 [41 32]
 [33 12]
 [13 31]
 [35 15]
 [18 46]
 [34 47]
 [12 42]
 [34 26]
 [27 42]
 [10 24]
 [48 12]
 [15 26]]
[[19 33 45]
 [14 21 38]
 [41 32 33]
 [12 13 31]
 [35 15 18]
 [46 34 47]
 [12 42 34]
 [26 27 42]
 [10 24 48]
 [12 15 26]]
[[19 33 45 14 21]
 [38 41 32 33 12]
 [13 31 35 15 18]
 [46 34 47 12 42]
 [34 26 27 42 10]
 [24 48 12 15 26]]
[[19 33 45 14 21 38]
 [41 32 33 12 13 31]
 [35 15 18 46 34 47]
 [12 42 34 26 27 42]
 [10 24 48 12 15 26]]
[[19 33 45 14 21 38 41 32 33 12]
 [13 31 35 15 18 46 34 47 12 42]
 [34 26 27 42 10 24 48 12 15 26]]
[[19 33 45 14 21 38 41 32 33 12 13 31 35 15 18]
 [46 34 47 12 42 34 26 27 42 10 24 48 12 15 26]]
[[19 33 45 14 21 38 41 32 33 12 13 31 35 15 18 46 34 47 12 42 34 26 27 42
  10 24 48 12 15 26]]
None


#### 3. Write a program to generate an array of 100 equally spaced numbers between 1 to 7 numbers of possible shapes.

e.g : np.linspace(1,7,100) # from 1 to 7 100 numbers (equally spaced)

In [109]:
def genShapes(a):
    """
        This function generates all possible of numpy array
        arg - numpy array
    """
    cnt = 1
    l = len(a)
    
    while cnt <= l:
        if l%cnt==0:
            x = int(l/cnt)
            y = cnt
            print(a.reshape(x,y))
        cnt+=1

a = np.linspace(1,7,100)
genShapes(a)

[[1.        ]
 [1.06060606]
 [1.12121212]
 [1.18181818]
 [1.24242424]
 [1.3030303 ]
 [1.36363636]
 [1.42424242]
 [1.48484848]
 [1.54545455]
 [1.60606061]
 [1.66666667]
 [1.72727273]
 [1.78787879]
 [1.84848485]
 [1.90909091]
 [1.96969697]
 [2.03030303]
 [2.09090909]
 [2.15151515]
 [2.21212121]
 [2.27272727]
 [2.33333333]
 [2.39393939]
 [2.45454545]
 [2.51515152]
 [2.57575758]
 [2.63636364]
 [2.6969697 ]
 [2.75757576]
 [2.81818182]
 [2.87878788]
 [2.93939394]
 [3.        ]
 [3.06060606]
 [3.12121212]
 [3.18181818]
 [3.24242424]
 [3.3030303 ]
 [3.36363636]
 [3.42424242]
 [3.48484848]
 [3.54545455]
 [3.60606061]
 [3.66666667]
 [3.72727273]
 [3.78787879]
 [3.84848485]
 [3.90909091]
 [3.96969697]
 [4.03030303]
 [4.09090909]
 [4.15151515]
 [4.21212121]
 [4.27272727]
 [4.33333333]
 [4.39393939]
 [4.45454545]
 [4.51515152]
 [4.57575758]
 [4.63636364]
 [4.6969697 ]
 [4.75757576]
 [4.81818182]
 [4.87878788]
 [4.93939394]
 [5.        ]
 [5.06060606]
 [5.12121212]
 [5.18181818]
 [5.24242424]
 [5.30

#### 4. Write a program to filter out all the numbers (generated from que.3) which is greater than 3.84 and less than 6.57.

In [96]:
op = a[(a> 3.84) & (a<6.57)]
print(op)

[3.84848485 3.90909091 3.96969697 4.03030303 4.09090909 4.15151515
 4.21212121 4.27272727 4.33333333 4.39393939 4.45454545 4.51515152
 4.57575758 4.63636364 4.6969697  4.75757576 4.81818182 4.87878788
 4.93939394 5.         5.06060606 5.12121212 5.18181818 5.24242424
 5.3030303  5.36363636 5.42424242 5.48484848 5.54545455 5.60606061
 5.66666667 5.72727273 5.78787879 5.84848485 5.90909091 5.96969697
 6.03030303 6.09090909 6.15151515 6.21212121 6.27272727 6.33333333
 6.39393939 6.45454545 6.51515152]


#### 5. Write a program to replace first 3 numbers with 100 and middle 3'numbers with 200 and last 3 numbers with 300 in output of que.5

In [110]:
def replaceNum(a):
    """
        replaces first 3 numbers with 100 and middle 3'numbers
        with 200 and last 3 numbers with 300
        arg- numpy array
    """
    a[:3] = 100
    a[49:52] = 200
    a[-1:-4:-1] = 300
    print(a)
    
replaceNum(a)

[100.         100.         100.           1.18181818   1.24242424
   1.3030303    1.36363636   1.42424242   1.48484848   1.54545455
   1.60606061   1.66666667   1.72727273   1.78787879   1.84848485
   1.90909091   1.96969697   2.03030303   2.09090909   2.15151515
   2.21212121   2.27272727   2.33333333   2.39393939   2.45454545
   2.51515152   2.57575758   2.63636364   2.6969697    2.75757576
   2.81818182   2.87878788   2.93939394   3.           3.06060606
   3.12121212   3.18181818   3.24242424   3.3030303    3.36363636
   3.42424242   3.48484848   3.54545455   3.60606061   3.66666667
   3.72727273   3.78787879   3.84848485   3.90909091 200.
 200.         200.           4.15151515   4.21212121   4.27272727
   4.33333333   4.39393939   4.45454545   4.51515152   4.57575758
   4.63636364   4.6969697    4.75757576   4.81818182   4.87878788
   4.93939394   5.           5.06060606   5.12121212   5.18181818
   5.24242424   5.3030303    5.36363636   5.42424242   5.48484848
   5.54545455   5.

#### 6. Write a program to create a 5x5 matrix of random int numbers between 10 to 100 and
- replace upper triangle with zeros and print as a new matrix
- replace lower triangle with zeros and print as a new matrix

In [81]:
a = np.random.randint(10,100,25).reshape(5,5)
print(a)

[[84 78 37 22 18]
 [93 21 28 22 60]
 [12 99 45 66 60]
 [13 45 68 93 20]
 [38 26 85 19 22]]


In [82]:
cnt = 0
b = a.copy()
for i in b:
    i[cnt+1:] = 0
    cnt+=1
print(b)

[[84  0  0  0  0]
 [93 21  0  0  0]
 [12 99 45  0  0]
 [13 45 68 93  0]
 [38 26 85 19 22]]


In [83]:
cnt = 0
c = a.copy()
for i in c:
    i[:cnt] = 0
    cnt+=1
print(c)

[[84 78 37 22 18]
 [ 0 21 28 22 60]
 [ 0  0 45 66 60]
 [ 0  0  0 93 20]
 [ 0  0  0  0 22]]


### Titanic Case Study


#### 7. Continue exercise on Titanic dataset and do followings:
- Generate various plots for each features (columns) and tell your conclusion
- Perform various grouping of for any 2 colmuns and provide your conclusions by plotting them
- Perform various grouping of for any 3 colmuns and provide your conclusions by plotting them
- Perform various grouping of for any 4 colmuns and provide your conclusions by plotting them

Notes:
- provide proper labeling for the data points
- provide proper labeling for x and y axis
- provide proper title for each graph
- Do not create any sublpot more than 4x3 area (12 grapphs and one subplot)


